name: CI - Continuous Integration

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-build:
    name: Lint & Build
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: 📦 Install
        run: npm ci --legacy-peer-deps

      - name: 🔍 Lint JS
        run: npm run lint:js
        continue-on-error: true

      - name: 🔍 Lint SCSS
        run: npm run lint:scss
        continue-on-error: true

      - name: 🏗️ Build
        run: npm run build

      - name: ✅ Verify Output
        run: |
          echo "✅ Verifying build output..."
          
          test -f dist/js/viks.js || exit 1
          test -f dist/js/viks.min.js || exit 1
          test -f dist/css/viks.css || exit 1
          test -f dist/css/viks.min.css || exit 1
          test -f dist/js/viks.js.map || exit 1
          test -f dist/js/viks.min.js.map || exit 1
          test -f dist/css/viks.css.map || exit 1
          test -f dist/css/viks.min.css.map || exit 1
          
          echo "✓ viks.js exists"
          echo "✓ viks.min.js exists"
          echo "✓ viks.css exists"
          echo "✓ viks.min.css exists"
          echo "✓ viks.js.map exists"
          echo "✓ viks.min.js.map exists"
          echo "✓ viks.css.map exists"
          echo "✓ viks.min.css.map exists"
          
          echo "✅ All files generated successfully!"